lines = [
  { from = 1, to = 2, resistance = 0.1 }
]

nodes = [
  { id = 0, position = "0+000", voltage = 0 }     # Jordnod
  { id = 1, position = "1+000", voltage = 0 }     # Matpunkt (från substation)
  { id = 2, position = "2+000", voltage = 0 }     # Lastpunkt (till tåg)
]

substations = [
  {
    id = "S1"
    fromNode = 0       # kopplad till jord
    toNode = 1         # matar in till nät
    emf = 1000         # [V]
    internalResistance = 0.05  # [Ohm]
  }
]

trains = [
  {
    id = "Train1"
    fromNode = 2       # lastens positiva sida
    toNode = 0         # tillbaka till jord
    # currentFunction kommer troligen konstrueras i kod, ej från config
  }
]
