grid {
  nodes = [
    { id: 0, voltage: 0.0, position: "1 0+ 0" },   // jord
    { id: 1, voltage: 0.0, position: "1 1+ 0" },
    { id: 2, voltage: 0.0, position: "1 2+ 0" }
  ]

  substations = [
    {
      id = "S1"
      nodeId = 0
      emf = 1000.0
      internalResistance = 0.1
    }
  ]

  trains = [
    { id = "T1", nodeId = 1 }
  ]

  lines = [
    { from = 0, to = 1, resistance = 0.01 },
    { from = 1, to = 2, resistance = 0.01 }
  ]
}
