dcsim {
  grid {
    referenceVoltage = 1000.0
    nodes = [
    { id = 0, position = "0+000", voltage = 0.0 },
    { id = 1, position = "0+000", voltage = 0.0 },
    { id = 2, position = "1+000", voltage = 0.0 }
    { id = 3, position = "3+000", voltage = 0.0 }
    ]

  lines = [
    { from = 1, to = 2, resistance = 0.1 },
    { from = 2, to = 3, resistance = 0.1 }
  ]

  substations = [
    { id = "S1", nodeId = 1, emf = 1000.0, internalResistance = 0.05 }
  ]

  templates = [
    { id = "T1", nodeId = 2 },
    { id = "T1", nodeId = 3 },
  ]
    devices = [
      { type = "train", id = "Train1", from = 2, to = 1 },
      { type = "train", id = "Train2", from = 2, to = 1 }
    ]
  }

  trains = [
    { id = "Train1", template = "T1", departure = 0.0 },
    { id = "Train2", template = "T1", departure = 60.0 }
  ]

  powerTemplates {
    basePath = "project/symphony/templates"
  }
}
